config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users
  get 'restaurant/index'

  resources :restaurants

  root 'restaurants#index'

end

app/models/restaurant.rb
class Restaurant < ActiveRecord::Base
	validates :name, presence: true,
	length: {minimum: 2 }

  belongs_to :owner
  has_many :reservations, :dependent => :destroy
  accepts_nested_attributes_for :reservations

  mount_uploader :image, ImageUploader
  mount_uploader :menu, MenuUploader
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

has_many :restaurants
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController
  def index
    @restaurant= Restaurant.all
  end

  def create
    @restaurant = Restaurant.new(restaurant_params)
    if @restaurant.save
      redirect_to restaurants_path(@restaurant)
    else
      # This line overrides the default rendering behavior, which
      # would have been to render the "create" view.
      redirect_to :back
    end 
    #create restraunt and redirect to Show
  end


  def edit
    @restaurant = Restaurant.find params[:id]
  end

  def update
    @restaurant = Restaurant.find(params[:id])
    
    if @restaurant.update!(restaurant_params)
      redirect_to restaurants_path(@restaurant)
    end
  end 


  def destroy
    #remove the  restaunratn from the list
    @restaurant = Restaurant.find params[:id]
    @restaurant.destroy
    redirect_to restaurants_path
  end

  def new
    @restaurant = Restaurant.new
  end


  def show

      @restaurant = Restaurant.find(params[:id])
  end

  private
    def restaurant_params
      params.require(:restaurant).permit(:name, :description, :address, :phone_number, :photo, :image, :menu)
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/restaurant_helper.rb
module RestaurantHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Blog</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <meta name="viewpoint" content="width=device-width, initital-scale=1.0">
</head>
<body>
<div class="navbar navbar-fixed-top ">
  <div class="navbar-inner ">
  	<div class="container">

  	<a class="btn btn-navbar" data-toggle="collapse"
        data-target=".nav=collapse">
        <span class="icon-bar"</span>
  		  <span class="icon-bar"</span>
  		  <span class="icon-bar"</span>
    </a>
    <a class="brand" href="#"> 
      Best Restaurants
    </a>
    <div class="nav-collapse">
    	<ul class="nav">
    	    <li><%= link_to "Browse Restaurants", restaurants_path %></li>
          <li><%= link_to "Restaurant Prices" %></li>
          <li><%= link_to "Contact Us" %></li>
          <li><%= link_to "Shopping Cart" %></li>
          <% if user_signed_in? %>
            <li class="welcome"> Welcome, <%=' '+current_user.email %><li>
            <li><%= link_to "Sign Out", destroy_user_session_path, method: :delete %><li>
          <% else %>
            <%= link_to "Sign In ", new_user_session_path  %>
          <% end %>
      <ul>
    </div>
  </div>
</div>

<% if notice %>
  <p class="alert alert-success"><%= notice %></p>
<% end %>
<% if alert %>
  <p class="alert alert-danger"><%= alert %></p>
<% end %>


<div class="container"> 
	<div class="row">
    <div id="user_nav">
      
      
      <div class="span9"><%= yield %></div>
      <div class="span3"></div>
      	<h2>About Us</h2>
      	Lorem ipsum dolor sit amet, consectetur.........
      	...........................
      	.............................
      	........................
      </div>
    </div>
</div>
</body>
</html>

app/views/restaurants/_form.html.erb
<%= form_for @restaurant, :html => { :class => 'form-horizontal', :multipart => true} do |f| %>
  <div class="control-group">
    <%= f.label :name, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :name, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :description, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :description, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :address, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :address, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :phone_number, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :phone_number, :class => 'text_field' %>
    </div>
  </div>

  <div class="control-group">
   <%= f.label :menu, :class => 'control-label' %>
    <div class="controls">
      <%= f.file_field :menu, :class => 'file_field' %>
    </div>
  </div>

   <div class="control-group"> 
   <%= f.label :image, :class => 'control-label' %>
    <div class="controls">
      <%= f.file_field :image, :class => 'file_field' %>
    </div>
  </div>

  <div class="form-actions">
    <%= f.submit nil, :class => 'btn btn-primary' %>
    <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                restaurants_path, :class => 'btn' %>

<% end %>

app/views/restaurants/edit.html.erb
<%- model_class =  Restaurant -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %>
	</h1>
</div>
<%= render :partial => 'form' %> 

app/views/restaurants/index.html.erb
<%- model_class = Restaurant -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th class='list-heading'><%= model_class.human_attribute_name(:id) %></th>
      <th class='list-heading'><%= model_class.human_attribute_name(:name) %></th>
      <th  class='list-heading'><%= model_class.human_attribute_name(:description) %></th>
      <th  class='list-heading'><%= model_class.human_attribute_name(:address) %></th>
      <th  class='list-heading'><%= model_class.human_attribute_name(:phone_number) %></th>
      <th  class='list-heading'><%= model_class.human_attribute_name(:created_at) %></th>
      <th  class='list-heading'><%= model_class.human_attribute_name(:restaurant) %></th>
      <th  class='list-heading'><%= model_class.human_attribute_name(:menu) %></th>
      <th  class='list-heading'><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @restaurant.each do |restaurant| %>
      <tr>
        <td><%= link_to restaurant.id, restaurant_path(restaurant) %></td>
        <td><%= restaurant.name %></td>
        <td><%= restaurant.description %></td>
        <td><%= restaurant.address %></td>
        <td><%= restaurant.phone_number %></td>
        <td><%= link_to time_ago_in_words(restaurant.created_at) +  "ago" %></td>
        <td><%= image_tag(restaurant.image_url(:thumb).to_s) %></td>
        <td><%= image_tag(restaurant.menu_url(:thumb_nail).to_s) %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_restaurant_path(restaurant), :class => 'btn btn-mini' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      restaurant_path(restaurant),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-mini btn-danger' %>
        </td>
      </tr>


    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_restaurant_path,
            :class => 'btn btn-primary' %>

app/views/restaurants/new.html.erb
<%- model_class = Restaurant -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/restaurants/show.html.erb
<%- model_class = Restaurant -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:name) %>:</strong></dt>
  <dd><%= @restaurant.name %></dd>
  <dt><strong><%= model_class.human_attribute_name(:description) %>:</strong></dt>
  <dd><%= @restaurant.description %></dd>
  <dt><strong><%= model_class.human_attribute_name(:address) %>:</strong></dt>
  <dd><%= @restaurant.address %></dd>
  <dt><strong><%= model_class.human_attribute_name(:phone_number) %>:</strong></dt>
	<dd><%= @restaurant.phone_number %></dd>
  <dt><strong><%= model_class.human_attribute_name("Menu") %></strong>
  <dd><%= @restaurant.image %></dd>
	<dt><strong><%= image_tag(@restaurant.menu_url, :width => 400) %></strong>
  <dd><%= @restaurant.menu %></dd>
  
</dl>

<div class="form-actions">
  <%= link_to t('.back', :default => t("helpers.links.back")),
              restaurants_path, :class => 'btn'  %>
  <%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_restaurant_path(@restaurant), :class => 'btn' %>
  <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              restaurant_path(@restaurant),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>
</div>
		<div class="actions">
			<%= link_to "edit", edit_restaurant_path(@restaurant) %>
			<%= link_to "remove", @restaurant, :confirm => 'Are you sure?', :method => :delete %>
		</div>

	<p>
		<%= link_to "Add a Restaurant Image", @new_restaurant_image_path, :restaurant_image_id => @restaurant_image %>
		<%= link_to "Remove Restaurant_Image", @restaurant_image, :confirm => "Are you sure?", :method => :delete %>
		<%= link_to "View Restaurant_Image", @restaurant_image_path %>
	</p>
</div>

app/views/welcome/index.html.erb
<h1>List of All Best Restaurants</h1>

#action to be shown then what will be shown
<%@restaurant.each do |restaurant|%> 
Restaurant<=% restaurant.name %>
Restaurant description <=% restaurant.description%>
Restaurant address <%= restaurant.address%>
Restaurant phone_number <%= restaurant.phone_number %>
<%end>